# Generated by Django 2.2.17 on 2021-01-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0013_auto_20200115_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemode',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='historicalcoursemode',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Price'),
        ),
    ]
